### ISSUE TITLE
The docs are out of date

### ISSUE THREAD

**Issue by Changaco** [liberapay/postgres.py#92]
@chadwhitacre [The docs](https://postgres-py.readthedocs.io/) are stuck at a two year old commit, but I don't have enough access to fix the issue. Can you look into it?

**Comment by chadwhitacre** [comment]
Looks like I can add you as a "Maintainer" on readthedocs.org and then you'll have access. I tried to add `changaco` but to no avail. Do you have an account there?

![Screen Shot 2019-10-21 at 11 52 59 PM](https://user-images.githubusercontent.com/134455/67258344-2d8f9b00-f45e-11e9-906a-3cdb702a7c95.png)

**Comment by Changaco** [comment]
My username on RtD is `Changaco`. I guess the lookup is case sensitive.

Fixing the problem may also require access to this repository's webhooks, but it looks like you can't give me that without transferring the repository to an organization that I "own".

**Comment by chadwhitacre** [comment]
> `Changaco`

I've added you as a maintainer on `postgres-py`, as well as on `Gratipay` and `environment-py`, the other two projects that the `Gratipay` user is also a maintainer for. Then I removed the `Gratipay` user as a maintainer. I also double-checked: you are already a maintainer on the rest of the projects I have on Read the Docs. Here's the full list:

- algorithm-py
- Aspen
- dependency-injection-py
- django-aspen
- environment-py
- filesystem-tree-py
- Flask-Aspen
- Gratipay
- Pando
- Postgres.py
- state-chain-py

> transferring the repository to an organization that I "own".

Here's an audit of what org/user owns the repo behind each Read the Docs project:

- algorithm-py — repo renamed, this should probably be deleted in favor of state-chain-py (below)
- Aspen — AspenWeb
- dependency-injection-py — AspenWeb
- django-aspen — AspenWeb
- environment-py — Gratipay
- filesystem-tree-py — AspenWeb
- Flask-Aspen — AspenWeb
- Gratipay — Gratipay ☺️ 
- Pando — AspenWeb
- Postgres.py — chadwhitacre
- state-chain-py — AspenWeb

@Changaco I've initiated a transfer of environment.py. I sent it to your personal GitHub account, since I don't have permission to create new public repos in @liberapay. I tried transferring postgres.py to you as well, but GitHub won't let me since you have a fork—even if I rename it. I guess the options are to a) remove your fork and transfer the original, or b) use your fork. :o)

**Comment by Changaco** [comment]
I've deleted my fork of postgres.py, and transferred environment.py to liberapay. If you transfer postgres.py to me then I'll transfer it to liberapay as well.

**Comment by chadwhitacre** [comment]
Done! :)

**Comment by Changaco** [comment]
Thanks Chad. I've updated the webhook, the docs for version 3.0.0 are now available.
